name: IceCream CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary: never
          generate-job-summary: false
          cache-read-only: false
      - name: Setup Git Config
        run: |
          git config --global user.email "ci@icecreammc.xyz"
          git config --global user.name "IceCream CI"
      - name: Get Build Number
        run: bash scripts/GetBuildNumber.sh
      - name: Apply Patches
        run: ./gradlew applyPatches
      - name: Create Paperclip Jar
        run: ./gradlew createMojmapPaperclipJar
        env:
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
      - name: Get Release Info
        run: bash scripts/GetReleaseInfo.sh
        env:
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.jar }}
          path: ${{ env.jar }}
      - name: Delete Draft Releases
        if: "!contains(github.event.commits[0].message, '[release-skip]')"
        continue-on-error: true
        uses: hugo19941994/delete-draft-releases@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Create Release
        if: "!contains(github.event.commits[0].message, '[release-skip]')"
        continue-on-error: true
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.jar }}
          bodyFile: ${{ env.info }}
          tag: ${{ env.tag }}
          name: ${{ env.name }}
          prerelease: ${{ env.pre }}
          token: ${{ secrets.TOKEN }}
          makeLatest: ${{ env.make_latest }}
      - name: Push to API
        if: "!contains(github.event.commits[0].message, '[release-skip]')"
        continue-on-error: true
        env:
          secret: ${{ secrets.API_PUSH_TOKEN }}
          secret_v2: ${{ secrets.API_V2_PUSH_TOKEN }}
          tag: ${{ env.tag }}
        run: sh scripts/PushToAPI.sh
